# Generated by Django 4.1.11 on 2023-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=100)),
                ('num_questions', models.IntegerField()),
                ('test_duration', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
