# Generated by Django 4.1.11 on 2023-09-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_questionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('selected_option', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
    ]
