# Generated by Django 4.1.11 on 2023-09-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_response_delete_questionresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='response',
            name='question_id',
            field=models.IntegerField(default=-1),
        ),
    ]
